version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      otel:
        patterns:
          - "go.opentelemetry.io/*"
      grpc:
        patterns:
          - "google.golang.org/grpc"
          - "google.golang.org/protobuf"
      prometheus:
        patterns:
          - "github.com/prometheus/*"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(actions)"
      include: "scope"
