run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - unconvert
    - unparam
    - whitespace
    - gocritic
    - gocyclo
    - godot
    - gosec
    - dupl

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - shadow

  gocyclo:
    min-complexity: 15

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

  revive:
    rules:
      - name: exported
        arguments:
          - checkPrivateReceivers
          - sayRepetitiveInsteadOfStutters

  gosec:
    excludes:
      - G104 # Audit errors not checked (we use errcheck for this)

issues:
  exclude-dirs:
    - examples
  exclude-files:
    - "examples/.*\\.go$"
  exclude-rules:
    - path: examples/
      linters:
        - typecheck
        - errcheck
        - gosimple
        - govet
        - ineffassign
        - staticcheck
        - unused
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - unparam
    - path: _bench_test\.go
      linters:
        - dupl
        - unparam
        - errcheck

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true